apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: voteapp
  name: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: voteapp
    spec:
      containers:
      - image: docker.io/httpd
        name: httpd
        resources: {}
status: {}
